#if !canImport(ObjectiveC)
import XCTest

extension ExplorerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExplorerTests = [
        ("test_currentDirectoryPath", test_currentDirectoryPath),
        ("test_delete_failure", test_delete_failure),
        ("test_delete_success", test_delete_success),
        ("test_writeWithOverwriteStrategy_successOnExistingFileExist", test_writeWithOverwriteStrategy_successOnExistingFileExist),
        ("test_writeWithSafeStrategy_failedBecauseFileExist", test_writeWithSafeStrategy_failedBecauseFileExist),
        ("test_writeWithSafeStrategy_failedOnFileManager", test_writeWithSafeStrategy_failedOnFileManager),
        ("test_writeWithSafeStrategy_success", test_writeWithSafeStrategy_success),
        ("test_writeWithSkipStrategy_successOnExistingFileExist", test_writeWithSkipStrategy_successOnExistingFileExist),
    ]
}

extension StringTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringTests = [
        ("test_withoutExtension_doubleExtension", test_withoutExtension_doubleExtension),
        ("test_withoutExtension_normal", test_withoutExtension_normal),
        ("test_withoutExtension_withoutExtensionItSelf", test_withoutExtension_withoutExtensionItSelf),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ExplorerTests.__allTests__ExplorerTests),
        testCase(StringTests.__allTests__StringTests),
    ]
}
#endif
