name: Generate Documentation

on:
  push:
    branches: 
      - master

jobs:
  upload_documentation:
    name: Generate upload_documentation
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Environment
      uses: gem install jazzy
    - name: Setup Project
      uses: swift package generate-xcodeproj
    - name: Generate Documentation
      uses: jazzy .
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs # The folder the action should deploy.