name: Swift

on: [push, pull_request]
      
jobs:
  linux_test:
    name: Linux Test
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Swift toolchain neccessary Depedencies
        run:  sudo apt-get install clang libcurl3 libcurl4-openssl-dev libpython2.7 libpython2.7-dev libicu-dev libstdc++6
      - name: CURL Swift Toolchain
        uses: wei/curl@master
          with:
            args: https://swift.org/builds/swift-5.1-release/ubuntu1604/swift-5.1-RELEASE/swift-5.1-RELEASE-ubuntu16.04.tar.gz 
      - name: Unzip Swift Toolchain
        run: tar xzf swift-5.1-RELEASE-ubuntu16.04.tar.gz
      - name: Add to PATH
        run: export PATH="$(pwd)/swift-5.1-RELEASE-ubuntu16.04/usr/bin:$PATH"
      - name: Update Package
        run: swift package update
      - name: Testing
        run: swift test
  macos_test:
    name: MacOS Test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
