name: Swift

on:
  push:
    branches: 
      - master
      - hotfix
  pull_request:
    branches: 
      - '*'
      
jobs:
  ubuntu_xenial_test:
    name: ubuntu_xenial Test
    runs-on: ubuntu-16.04
    container: 
      image: vapor/swift:5.2-xenial
    steps:
        - uses: actions/checkout@v2
        - run: swift test
  ubuntu_bionic_test:
    name: ubuntu_xenial Test
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - run: swift test
  macos_test:
    name: MacOS Test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test
