name: Explorer CI

on:
  push:
    branches: 
      - master
      - hotfix
  pull_request:
    branches: 
      - '*'
      
jobs:
  ubuntu_xenial_test:
    name: Ubuntu-16.04 Unit Test
    runs-on: ubuntu-16.04
    container: 
      image: vapor/swift:5.2-xenial
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Testing
      run: make test
    - name: Uploading Code Coverage
      run: llvm-cov export -format="lcov" .build/debug/ExplorerPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov; bash <(curl https://codecov.io/bash)

  ubuntu_bionic_test:
    name: Ubuntu-18.04 Unit Test
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Testing
      run: make test
    - name: Uploading Code Coverage
      run: llvm-cov export -format="lcov" .build/debug/ExplorerPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov; bash <(curl https://codecov.io/bash)

  macos_test:
    name: MacOS Unit Test
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Testing
      run: make test
